version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    groups:
      test-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /clients/react-native
    schedule:
      interval: weekly
    groups:
      react-native-client-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
    groups:
      mobile-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      container-bases:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-actions:
        patterns:
          - "*"
