// @ts-check
import { test, expect } from '@playwright/test';
import { resolveTestConfig } from '../helpers/config.js';
import { buildAdminUser, openDashboardShell } from '../helpers/fixtures.js';

const config = resolveTestConfig();
const adminUser = buildAdminUser(config);

const elementIds = Object.freeze([
  'user-avatar',
  'user-name',
  'user-email',
  'user-role',
  'new-site-button',
  'delete-site-button',
  'site-created-at',
  'site-status',
  'site-form',
  'edit-site-name',
  'edit-site-origin',
  'edit-site-owner',
  'sites-list',
  'empty-sites-message',
  'site-search-toggle-button',
  'site-search-input',
  'dashboard-section-tabs',
  'dashboard-section-tab-feedback',
  'dashboard-section-tab-subscriptions',
  'dashboard-section-tab-traffic',
  'dashboard-section-tab-sentry',
  'widget-test-button',
  'copy-widget-snippet',
  'widget-snippet',
  'widget-show-message-input',
  'widget-show-sentiment-buttons',
  'subscribe-test-button',
  'copy-subscribe-widget-snippet',
  'subscribe-widget-snippet',
  'traffic-test-button',
  'copy-traffic-widget-snippet',
  'traffic-widget-snippet',
  'site-dashboard-view',
  'all-sites-traffic-view',
  'all-sites-traffic-back-button',
  'global-traffic-report-library',
  'global-traffic-reports-list',
  'global-traffic-report-create-button',
  'global-traffic-report-title',
  'global-traffic-report-name',
  'global-traffic-report-type-chip',
  'global-traffic-report-sites-chip',
  'global-traffic-report-schedule-chip',
  'global-traffic-report-sites-summary',
  'global-traffic-report-select-all-sites',
  'global-traffic-report-clear-sites',
  'global-traffic-report-sites-list',
  'traffic-report-title',
  'settings-open-all-sites-traffic',
  'all-sites-traffic-report-enabled',
  'all-sites-traffic-report-frequency-daily',
  'all-sites-traffic-report-frequency-weekly',
  'all-sites-traffic-report-frequency-monthly',
  'all-sites-traffic-report-send-time',
  'all-sites-traffic-report-timezone',
  'all-sites-traffic-report-weekday',
  'all-sites-traffic-report-month-day',
  'all-sites-traffic-report-recipient',
  'all-sites-traffic-report-status',
  'all-sites-traffic-report-email-state',
  'all-sites-traffic-report-next-send',
  'all-sites-traffic-report-last-sent',
  'all-sites-traffic-report-test-button',
  'all-sites-visit-count',
  'all-sites-unique-visitor-count',
  'all-sites-site-count',
  'all-sites-traffic-status',
  'all-sites-traffic-trend-chart',
  'all-sites-traffic-sites-table-body',
  'sentry-ingest-endpoint',
  'sentry-ingest-token',
  'sentry-browser-snippet',
  'rotate-sentry-token-button',
  'sentry-issues-table-body',
  'sentry-issue-detail',
  'feedback-table-body',
  'subscribers-table-body',
  'top-pages-table-body',
  'visit-count',
  'unique-visitor-count',
  'feedback-count',
  'subscriber-count',
  'traffic-status',
  'messages-search-toggle-button',
  'messages-search-input',
  'session-timeout-notification',
  'session-timeout-confirm-button',
  'session-timeout-dismiss-button',
  'settings-modal',
  'settings-auto-logout-enabled',
  'settings-auto-logout-prompt-seconds',
  'settings-auto-logout-logout-seconds'
]);

test('dashboard renders the expected shell element ids', async ({ page }) => {
  await openDashboardShell(page, config, adminUser);

  for (const elementId of elementIds) {
    await expect(page.locator(`#${elementId}`)).toHaveCount(1);
  }
});
